apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chatbot-ingress
  namespace: chatbot-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: 203.230.103.28
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ki-chat
            port:
              number: 80