apiVersion: v1
kind: Service
metadata:
  name: ki-chat-nodeport
  namespace: chatbot-app
spec:
  type: NodePort
  selector:
    app: ki-chat
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30004
    protocol: TCP